#!/usr/bin/env bash
# Wasted Spend — one-command bootstrap. Idempotent: safe to re-run anytime.
# Fresh clone → running stack + SQL layer + accounts + RCA agent.
set -euo pipefail
cd "$(dirname "$0")"

DEMO_EMAIL="${DEMO_EMAIL:-wastedspend.demo@gmail.com}"
DEMO_PASSWORD="${DEMO_PASSWORD:-WastedSpend!2026}"
UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36'

say()  { printf '\n\033[1m▸ %s\033[0m\n' "$*"; }
ok()   { printf '  ✓ %s\n' "$*"; }
die()  { printf '  ✗ %s\n' "$*" >&2; exit 1; }

wait_http() { # url [tries]
  local url=$1 tries=${2:-60}
  for _ in $(seq "$tries"); do
    curl -sf --max-time 3 "$url" >/dev/null 2>&1 && return 0
    sleep 3
  done
  return 1
}

# ── 0. prerequisites ─────────────────────────────────────────────────────────
say "checking prerequisites"
command -v docker >/dev/null || die "docker not found — install Docker Desktop"
docker info >/dev/null 2>&1 || die "docker daemon not running — start Docker Desktop"
command -v node >/dev/null || die "node not found — install Node.js ≥ 23"
node -e 'process.exit(+process.versions.node.split(".")[0] >= 23 ? 0 : 1)' \
  || die "node ≥ 23 required (native TypeScript), found $(node --version)"
ok "docker + node $(node --version)"

# ── 1. .env ──────────────────────────────────────────────────────────────────
say "secrets (.env)"
if [ ! -f .env ]; then
  cat > .env <<EOF
# generated by bootstrap.sh $(date +%F)
CLICKHOUSE_PASSWORD=wastedspend_ch

LANGFUSE_SALT=$(openssl rand -hex 16)
LANGFUSE_ENCRYPTION_KEY=$(openssl rand -hex 32)
LANGFUSE_NEXTAUTH_SECRET=$(openssl rand -hex 32)
LANGFUSE_PUBLIC_KEY=pk-lf-wastedspend-demo-2026
LANGFUSE_SECRET_KEY=sk-lf-wastedspend-demo-2026
LANGFUSE_ADMIN_EMAIL=${DEMO_EMAIL}
LANGFUSE_ADMIN_PASSWORD=${DEMO_PASSWORD}
REDIS_AUTH=wastedspend_redis
MINIO_ROOT_PASSWORD=wastedspend_minio

# filled automatically in step 3:
HYPERDX_INGESTION_API_KEY=

LITELLM_MASTER_KEY=sk-$(openssl rand -hex 16)

# free-tier keys (console.groq.com / aistudio.google.com) — optional,
# the mock-pro model works without any:
GROQ_API_KEY=
GEMINI_API_KEY=
EOF
  ok "generated .env (add GROQ_API_KEY / GEMINI_API_KEY for real models)"
else
  ok ".env exists — leaving it alone"
fi
# shellcheck disable=SC1091
set -a; source .env; set +a

# ── 2. the stack ─────────────────────────────────────────────────────────────
say "starting the stack (first run pulls ~6 GB)"
docker compose up -d
wait_http http://localhost:8123/ping 100 || die "clickhouse didn't come up"
ok "clickhouse"
wait_http http://localhost:3000/api/public/health 100 || die "langfuse didn't come up"
ok "langfuse"
wait_http http://localhost:8080 100 || die "hyperdx didn't come up"
ok "hyperdx"
wait_http http://localhost:3080/health 100 || die "librechat didn't come up"
ok "librechat"

# ── 3. ClickStack ingestion key (minted by first HyperDX user) ───────────────
say "hyperdx admin + OTLP ingestion key"
curl -s --max-time 10 -X POST http://localhost:8000/register/password \
  -H 'Content-Type: application/json' \
  -d "{\"email\":\"$DEMO_EMAIL\",\"password\":\"$DEMO_PASSWORD\",\"confirmPassword\":\"$DEMO_PASSWORD\"}" \
  >/dev/null 2>&1 || true   # fails harmlessly if already registered
KEY=$(docker compose exec -T hyperdx-db mongosh --quiet hyperdx \
      --eval 'print(db.teams.findOne()?.apiKey ?? "")' | tr -d '[:space:]')
[ -n "$KEY" ] || die "could not read ingestion key from hyperdx mongo"
if [ "${HYPERDX_INGESTION_API_KEY:-}" != "$KEY" ]; then
  if grep -q '^HYPERDX_INGESTION_API_KEY=' .env; then
    sed -i '' "s|^HYPERDX_INGESTION_API_KEY=.*|HYPERDX_INGESTION_API_KEY=$KEY|" .env 2>/dev/null \
      || sed -i "s|^HYPERDX_INGESTION_API_KEY=.*|HYPERDX_INGESTION_API_KEY=$KEY|" .env
  else
    echo "HYPERDX_INGESTION_API_KEY=$KEY" >> .env
  fi
  export HYPERDX_INGESTION_API_KEY="$KEY"
  docker compose up -d librechat >/dev/null   # picks up the key for OTLP export
  wait_http http://localhost:3080/health 60 || die "librechat didn't restart"
  ok "ingestion key installed: ${KEY:0:8}… (librechat restarted)"
else
  ok "ingestion key already current"
fi

# ── 4. the SQL layer ─────────────────────────────────────────────────────────
say "applying the SQL layer"
for f in sql/05_readonly_user.sql sql/10_unified_spans.sql \
         sql/20_golden_signals.sql sql/30_wasted_spend.sql sql/03_stitch_fallback.sql; do
  docker compose exec -T clickhouse clickhouse-client \
    --password "$CLICKHOUSE_PASSWORD" -n < "$f" || die "failed applying $f"
  ok "$f"
done

# ── 5. app account ───────────────────────────────────────────────────────────
say "librechat demo account"
curl -s --max-time 10 -X POST http://localhost:3080/api/auth/register \
  -H 'Content-Type: application/json' -H "User-Agent: $UA" \
  -d "{\"name\":\"Demo\",\"username\":\"demo\",\"email\":\"$DEMO_EMAIL\",\"password\":\"$DEMO_PASSWORD\",\"confirm_password\":\"$DEMO_PASSWORD\"}" \
  >/dev/null 2>&1 || true   # fails harmlessly if already registered
curl -s --max-time 10 -X POST http://localhost:3080/api/auth/login \
  -H 'Content-Type: application/json' -H "User-Agent: $UA" \
  -d "{\"email\":\"$DEMO_EMAIL\",\"password\":\"$DEMO_PASSWORD\"}" \
  | grep -q '"token"' || die "librechat login failed for $DEMO_EMAIL"
ok "login works: $DEMO_EMAIL"

# ── 6. the RCA agent ─────────────────────────────────────────────────────────
say "cost detective agent"
wait_http http://localhost:8100/health 40 || die "rca-tools MCP server not healthy"
LOADGEN_EMAIL="$DEMO_EMAIL" LOADGEN_PASSWORD="$DEMO_PASSWORD" node agent/create-agent.ts
ok "agent ready"

# ── done ─────────────────────────────────────────────────────────────────────
say "bootstrap complete"
cat <<EOF

  LibreChat   http://localhost:3080   ($DEMO_EMAIL / $DEMO_PASSWORD)
  Langfuse    http://localhost:3000   (same login)
  HyperDX     http://localhost:8080   (same login)
  ClickHouse  http://localhost:8123/play  (default / $CLICKHOUSE_PASSWORD)

  next:
    node dashboard/server.ts     # burn console → http://localhost:8090
    node loadgen/loadgen.ts      # simulated traffic
    LOADGEN_PATIENCE_S=3 node loadgen/loadgen.ts   # → wasted spend climbs

  all details: docs/ACCESS.md
EOF
